### PR TITLE
fix(types): limit recursion in types using ternary statements

### LINKED ISSUE #926: Memory leak/recursive loop in 12.0.7 in the types
@octokit/webhooks v. 12.0.7 seems to introduce some kind of memory leak/recursive loop. v 12.0.6 still works. 

_Originally posted by @Uzlopak in https://github.com/probot/probot/pull/1926#issuecomment-1819771230_

### PR DESCRIPTION
**Pull request by Uzlopak**
Resolves #926

@wolfy1339 

It seems that this results in building again properly on probot. 
But I dont know if this is what you expect.

I used `npm link` to test if it builds again in probot. And it builds again

----

### Before the change?

* 

### After the change?

* 

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

File: src/event-handler/index.ts [hunk 1]
```diff
@@ -15,12 +15,18 @@ import {
 import { receiverHandle as receive } from "./receive.js";
 import { removeListener } from "./remove-listener.js";
 
-interface EventHandler<TTransformed> {
+interface EventHandler<TTransformed = unknown> {
```
Comment (wolfy1339) [inline src/event-handler/index.ts]: Just wondering if it's necessary for this value to be optional? As this interface is never called on it's own, and `TTransformed` is always passed down

Comment (Uzlopak) [reply src/event-handler/index.ts]: i think it is an artifact from my testing
```suggestion
interface EventHandler<TTransformed> {
```

**Review by wolfy1339 — APPROVED** [review]
