### PR TITLE
fix: handle missing `Content-Type` header with `null` check

### LINKED ISSUE #804: [BUG]: Missing null check for content-type header causes unhandled TypeError exception
### What happened?

1. Submit a blank POST request to a listening webhook endpoint  e.g. "curl -X POST localhost/api/github/webhooks"
2. Note the unhandled TypeError exception thrown.

### Versions

octokit/webhooks.js v10.5.1+, v11.0.0-beta.5

### Relevant log output

```shell
[@octokit/webhooks] `onUnhandledRequest()` is deprecated and will be removed in a future release of `@octokit/webhooks`
/home/asdf/LocalProjects/codeql-git-app/node_modules/@octokit/webhooks/dist-node/index.js:256
  if (!request.headers["content-type"].startsWith("application/json")) {
                                       ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at middleware (/home/asdf/LocalProjects/codeql-git-app/node_modules/@octokit/webhooks/dist-node/index.js:256:40)
    at middleware (/home/asdf/LocalProjects/codeql-git-app/node_modules/@octokit/app/dist-node/index.js:213:12)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:1065:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)

Node.js v18.13.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mikey923**
Resolves #804

----

### Before the change?
Submitting a POST request to listening webhook endpoints with no content-type header can cause DOS conditions due to missing null check in middleware handler.

### After the change?
Submitting a POST request to listening webhook endpoints with no content-type header behaves the same as if you had submitted any other non-"application/json" content-type header and supplies a friendly error message.

### Other information
Introduced by https://github.com/octokit/webhooks.js/commit/b7aee15b00537e2ec655eb461892b8b42005495c

----

### Pull request checklist
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?
- [ ] Yes (Please add the `Type: Breaking change` label)
- [X] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
I can't seem to set the label :(
----

### CODE REVIEW

**Review by wolfy1339 — DISMISSED** [review]

File: src/middleware/node/middleware.ts [hunk 1]
```diff
@@ -47,7 +47,10 @@ export async function middleware(
   // Check if the Content-Type header is `application/json` and allow for charset to be specified in it
   // Otherwise, return a 415 Unsupported Media Type error
   // See https://github.com/octokit/webhooks.js/issues/158
-  if (!request.headers["content-type"].startsWith("application/json")) {
+  if (
+    request.headers["content-type"] == null ||
```
Comment (gr2m) [inline src/middleware/node/middleware.ts]: why not check if it's falsy?
```suggestion
    !request.headers["content-type"] ||
```

Comment (mikey923) [reply src/middleware/node/middleware.ts]: Because I am bouncing between too many languages!  You are absolutely correct.

**Review by wolfy1339 — APPROVED** [review]

**Comment by mikey923** [comment]
Thank you for the quick feedback!  Looking forward to using this more.
